language: python
python:
  - 3.4
  - 3.5
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - flake8 sockjs
  - coverage run --source=sockjs setup.py test
  - coverage report
  - python setup.py check -rm
